# 01 - Statcast Data Collection

This notebook collects an initial sample of MLB Statcast data and explores its structure before building the full dataset.

In [2]:
import pandas as pd
import numpy as np
from pybaseball import statcast

pd.set_option("display.max_columns", None)

## Initial Data Sample

Start with a small date range to understand the Statcast data before collecting full seasons.

In [3]:
sample = statcast(
    start_dt="2025-06-01",
    end_dt="2025-06-03"
)

This is a large query, it may take a moment to complete

100%|██████████| 3/3 [00:07<00:00,  2.59s/it]

In [4]:
sample.shape

(10731, 119)

## Raw Data

Inspect the raw Statcast data and available variables.

In [5]:
sample.head()

,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,description,spin_dir,spin_rate_deprecated,break_angle_deprecated,break_length_deprecated,zone,des,game_type,stand,p_throws,home_team,away_team,type,hit_location,bb_type,balls,strikes,game_year,pfx_x,pfx_z,plate_x,plate_z,on_3b,on_2b,on_1b,outs_when_up,inning,inning_topbot,hc_x,hc_y,tfs_deprecated,tfs_zulu_deprecated,umpire,sv_id,vx0,vy0,vz0,ax,ay,az,sz_top,sz_bot,hit_distance_sc,launch_speed,launch_angle,effective_speed,release_spin_rate,release_extension,game_pk,fielder_2,fielder_3,fielder_4,fielder_5,fielder_6,fielder_7,fielder_8,fielder_9,release_pos_y,estimated_ba_using_speedangle,estimated_woba_using_speedangle,woba_value,woba_denom,babip_value,iso_value,launch_speed_angle,at_bat_number,pitch_number,pitch_name,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment,spin_axis,delta_home_win_exp,delta_run_exp,bat_speed,swing_length,miss_distance,estimated_slg_using_speedangle,delta_pitcher_run_exp,hyper_speed,home_score_diff,bat_score_diff,home_win_exp,bat_win_exp,age_pit_legacy,age_bat_legacy,age_pit,age_bat,n_thruorder_pitcher,n_priorpa_thisgame_player_at_bat,pitcher_days_since_prev_game,batter_days_since_prev_game,pitcher_days_until_next_game,batter_days_until_next_game,api_break_z_with_gravity,api_break_x_arm,api_break_x_batter_in,arm_angle,attack_angle,attack_direction,swing_path_tilt,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
3752,SI,2025-06-03,90.1,-4.21,3.69,"Thompson, Ryan",669221,657044,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,13,"Sean Murphy grounds out, third baseman Eugenio...",R,R,R,ATL,AZ,X,5,ground_ball,1,0,2025,-1.27,-0.37,-1.009025,2.494118,<NA>,<NA>,<NA>,2,9,Bot,97.13,167.74,<NA>,<NA>,<NA>,<NA>,10.729945,-130.757295,3.887809,-16.871066,27.800732,-37.594837,3.4,1.64,7,56.2,-18,90.7,2041,6.8,777672,672515,647304,606466,553993,672695,694374,677950,682998,53.66,0.058,0.056,0.0,1,0,0,1,75,2,Sinker,3,8,3,8,8,3,3,8,Standard,Standard,277,-0.001,-0.297,74.9,7.1,<NA>,0.058,0.297,88.0,-5,-5,0.001,0.001,33,30,33,31,1,0,4,2,1,1,3.2,1.27,1.27,-12.6,4.595315,3.409159,34.295375,28.827026,28.231081
3917,SI,2025-06-03,90.3,-4.07,3.72,"Thompson, Ryan",669221,657044,NaN,ball,<NA>,<NA>,<NA>,<NA>,13,NaN,R,R,R,ATL,AZ,B,<NA>,NaN,0,0,2025,-0.99,-0.64,-0.391714,1.236208,<NA>,<NA>,<NA>,2,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,11.274958,-130.970171,1.186299,-13.789693,28.278903,-39.996444,3.19791,1.524625,<NA>,<NA>,<NA>,90.3,1902,6.5,777672,672515,647304,606466,553993,672695,694374,677950,682998,53.96,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,75,1,Sinker,3,8,3,8,8,3,3,8,Standard,Standard,278,0.0,0.037,<NA>,<NA>,<NA>,<NA>,-0.037,<NA>,-5,-5,0.001,0.001,33,30,33,31,1,0,4,2,1,1,3.45,0.99,0.99,-11.6,<NA>,<NA>,<NA>,<NA>,<NA>
3996,SI,2025-06-03,89.6,-4.1,3.74,"Thompson, Ryan",657077,657044,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,5,"Alex Verdugo grounds out softly, pitcher Ryan ...",R,L,R,ATL,AZ,X,1,ground_ball,0,0,2025,-0.96,-0.45,-0.25095,2.36659,<NA>,<NA>,<NA>,1,9,Bot,126.18,188.73,<NA>,<NA>,<NA>,<NA>,11.588981,-129.988833,3.619609,-13.243571,26.098634,-38.313268,3.54,1.61,1,59.9,-64,90.2,1831,6.7,777672,672515,647304,606466,553993,672695,694374,677950,682998,53.76,0.243,0.224,0.0,1,0,0,2,74,1,Sinker,3,8,3,8,8,3,3,8,Infield shade,Standard,278,-0.002,-0.254,<NA>,<NA>,<NA>,0.243,0.254,88.0,-5,-5,0.003,0.003,33,29,33,29,1,3,4,3,1,1,3.3,0.96,-0.96,-12.8,<NA>,<NA>,<NA>,<NA>,<NA>
4192,SI,2025-06-03,91.3,-4.07,3.7,"Thompson, Ryan",645277,657044,field_out,hit_into_play,<NA>,<NA>,<NA>,<NA>,9,Ozzie Albies grounds out to first baseman Josh...,R,L,R,ATL,AZ,X,3,ground_ball,0,1,2025,-0.88,-0.65,0.289465,1.88225,<NA>,<NA>,<NA>,0,9,Bot,158.61,165.27,<NA>,<NA>,<NA>,<NA>,13.040729,-132.257498,2.820765,-13.101519,28.09278,-40.683379,3.27,1.6,57,86.3,3,92.5,1976,7.2,777672,672515,647304,606466,553993,672695,694374,677950,682998,53.28,0.33,0.297,0.0,1,0,0,2,73,2,Sinker,3,8,3,8,8,3,3,8,Infield shade,Standard,278,-0.004,-0.22,73.3,7.4,<NA>,0.352,0.22,88.0,-5,-5,0.007,0.007,33,28,33,28,1,3,4,2,1,1,3.41,0.88,-0.88,-13.1,10.267937,-2.231143,38.851363,26.967882,32.795806
4282,SI,2025-06-03,91.1,-4.16,3.73,"Thompson, Ryan",645277,657044,NaN,called_strike,<NA>,<NA>,<NA>,<NA>,6,NaN,R,L,R,ATL,AZ,S,<NA>,NaN,0,0,2025,-1.26,-0.52,0.675707,2.217944,<NA>,<NA>,<NA>,0,9,Bot,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.928065,-131.653867,3.391099,-17.943488,29.367677,-39.327032,3.061638,1.410388,<NA>,<NA>,<NA>,91.3,1964,6.9,777672,672515,647304,606466,553993,672695,694374,677950,682998,53.6,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,73,1,Sinker,3,8,3,8,8,3,3,8,Infield shade,Standard,275,-0.001,-0.039,<NA>,<NA>,<NA>,<NA>,0.039,<NA>,-5,-5,0.008,0.008,33,28,33,28,1,3,4,2,1,1,3.32,1.26,-1.26,-12.6,<NA>,<NA>,<NA>,<NA>,<NA>

In [6]:
sample.columns.tolist()

['pitch_type',
 'game_date',
 'release_speed',
 'release_pos_x',
 'release_pos_z',
 'player_name',
 'batter',
 'pitcher',
 'events',
 'description',
 'spin_dir',
 'spin_rate_deprecated',
 'break_angle_deprecated',
 'break_length_deprecated',
 'zone',
 'des',
 'game_type',
 'stand',
 'p_throws',
 'home_team',
 'away_team',
 'type',
 'hit_location',
 'bb_type',
 'balls',
 'strikes',
 'game_year',
 'pfx_x',
 'pfx_z',
 'plate_x',
 'plate_z',
 'on_3b',
 'on_2b',
 'on_1b',
 'outs_when_up',
 'inning',
 'inning_topbot',
 'hc_x',
 'hc_y',
 'tfs_deprecated',
 'tfs_zulu_deprecated',
 'umpire',
 'sv_id',
 'vx0',
 'vy0',
 'vz0',
 'ax',
 'ay',
 'az',
 'sz_top',
 'sz_bot',
 'hit_distance_sc',
 'launch_speed',
 'launch_angle',
 'effective_speed',
 'release_spin_rate',
 'release_extension',
 'game_pk',
 'fielder_2',
 'fielder_3',
 'fielder_4',
 'fielder_5',
 'fielder_6',
 'fielder_7',
 'fielder_8',
 'fielder_9',
 'release_pos_y',
 'estimated_ba_using_speedangle',
 'estimated_woba_using_speedangle',
 'woba_value',
 'woba_denom',
 'babip_value',
 'iso_value',
 'launch_speed_angle',
 'at_bat_number',
 'pitch_number',
 'pitch_name',
 'home_score',
 'away_score',
 'bat_score',
 'fld_score',
 'post_away_score',
 'post_home_score',
 'post_bat_score',
 'post_fld_score',
 'if_fielding_alignment',
 'of_fielding_alignment',
 'spin_axis',
 'delta_home_win_exp',
 'delta_run_exp',
 'bat_speed',
 'swing_length',
 'miss_distance',
 'estimated_slg_using_speedangle',
 'delta_pitcher_run_exp',
 'hyper_speed',
 'home_score_diff',
 'bat_score_diff',
 'home_win_exp',
 'bat_win_exp',
 'age_pit_legacy',
 'age_bat_legacy',
 'age_pit',
 'age_bat',
 'n_thruorder_pitcher',
 'n_priorpa_thisgame_player_at_bat',
 'pitcher_days_since_prev_game',
 'batter_days_since_prev_game',
 'pitcher_days_until_next_game',
 'batter_days_until_next_game',
 'api_break_z_with_gravity',
 'api_break_x_arm',
 'api_break_x_batter_in',
 'arm_angle',
 'attack_angle',
 'attack_direction',
 'swing_path_tilt',
 'intercept_ball_minus_batter_pos_x_inches',
 'intercept_ball_minus_batter_pos_y_inches']

## Relevant Variables

Keep an initial set of variables related to pitch characteristics, movement, location, context, and outcomes.

In [7]:
columns_to_keep = [
    "game_date",
    "player_name",
    "pitcher",
    "batter",
    "pitch_type",
    "release_speed",
    "release_spin_rate",
    "pfx_x",
    "pfx_z",
    "release_pos_x",
    "release_pos_z",
    "release_extension",
    "plate_x",
    "plate_z",
    "zone",
    "stand",
    "p_throws",
    "balls",
    "strikes",
    "description",
    "events"
]

In [9]:
pitch_data = sample[columns_to_keep].copy()
pitch_data.head(10)

,game_date,player_name,pitcher,batter,pitch_type,release_speed,release_spin_rate,pfx_x,pfx_z,release_pos_x,release_pos_z,release_extension,plate_x,plate_z,zone,stand,p_throws,balls,strikes,description,events
3752,2025-06-03,"Thompson, Ryan",657044,669221,SI,90.1,2041,-1.27,-0.37,-4.21,3.69,6.8,-1.009025,2.494118,13,R,R,1,0,hit_into_play,field_out
3917,2025-06-03,"Thompson, Ryan",657044,669221,SI,90.3,1902,-0.99,-0.64,-4.07,3.72,6.5,-0.391714,1.236208,13,R,R,0,0,ball,NaN
3996,2025-06-03,"Thompson, Ryan",657044,657077,SI,89.6,1831,-0.96,-0.45,-4.1,3.74,6.7,-0.25095,2.36659,5,L,R,0,0,hit_into_play,field_out
4192,2025-06-03,"Thompson, Ryan",657044,645277,SI,91.3,1976,-0.88,-0.65,-4.07,3.7,7.2,0.289465,1.88225,9,L,R,0,1,hit_into_play,field_out
4282,2025-06-03,"Thompson, Ryan",657044,645277,SI,91.1,1964,-1.26,-0.52,-4.16,3.73,6.9,0.675707,2.217944,6,L,R,0,0,called_strike,NaN
4180,2025-06-03,"Blewett, Scott",656240,672695,SL,84.6,2046,0.13,-0.22,-2.16,6.24,7.0,0.001471,2.47185,5,L,R,0,1,hit_into_play,field_out
4281,2025-06-03,"Blewett, Scott",656240,672695,FF,92.7,2192,-0.25,1.05,-2.16,6.29,7.1,-0.713451,3.453864,1,L,R,0,0,called_strike,NaN
1397,2025-06-03,"Montero, Rafael",606160,606466,FS,89.4,1461,-0.63,0.09,-1.49,5.01,6.2,-0.097533,2.536743,5,L,R,3,2,hit_into_play,single
1425,2025-06-03,"Montero, Rafael",606160,606466,FF,96.1,2310,-0.84,1.07,-1.6,5.19,6.2,0.19282,2.763668,5,L,R,3,2,foul,NaN
1480,2025-06-03,"Montero, Rafael",606160,606466,FS,88.6,1598,-0.91,0.09,-1.29,5.01,6.5,-0.09467,1.973839,8,L,R,3,2,foul,NaN

In [11]:
print("Number of pitches:", len(pitch_data))
print("Number of columns:", len(pitch_data.columns))
pitch_data.info()

Number of pitches: 10731
Number of columns: 21
<class 'pandas.DataFrame'>
Index: 10731 entries, 3752 to 4147
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   game_date          10731 non-null  str
 1   player_name        10731 non-null  str
 2   pitcher            10731 non-null  Int64
 3   batter             10731 non-null  Int64
 4   pitch_type         10704 non-null  str
 5   release_speed      10702 non-null  Float64
 6   release_spin_rate  10684 non-null  Int64
 7   pfx_x              10702 non-null  Float64
 8   pfx_z              10702 non-null  Float64
 9   release_pos_x      10702 non-null  Float64
 10  release_pos_z      10702 non-null  Float64
 11  release_extension  10704 non-null  Float64
 12  plate_x            10704 non-null  Float64
 13  plate_z            10704 non-null  Float64
 14  zone               10704 non-null  Int64
 15  stand              10731 non-null  str
 16  p_throws           10731 non-null  str
 17  balls              10731 non-null  Int64
 18  strikes            10731 non-null  Int64
 19  description        10731 non-null  str
 20  events             2766 non-null   str
dtypes: Float64(8), Int64(6), str(7)
memory usage: 2.3 MB

## Pitch Types

Since the project will eventually evaluate individual pitches and complete arsenals, I first want to understand which pitch types appear in the sample.

In [12]:
pitch_data["pitch_type"].value_counts()

pitch_type
FF    3290
SI    1724
SL    1556
CH    1061
ST     913
FC     893
CU     677
FS     370
KC     177
SV      27
EP       9
CS       5
PO       2
Name: count, dtype: int64

## Pitch Outcomes

The `description` variable records the result of an individual pitch. Understanding these outcomes will be important when deciding how pitch effectiveness should eventually be modeled.

In [13]:
pitch_data["description"].value_counts()

description
ball                       3620
foul                       1903
hit_into_play              1893
called_strike              1746
swinging_strike            1082
blocked_ball                225
foul_tip                    120
swinging_strike_blocked      63
hit_by_pitch                 26
automatic_ball               23
foul_bunt                    19
missed_bunt                   4
automatic_strike              4
pitchout                      2
bunt_foul_tip                 1
Name: count, dtype: int64

In [14]:
pitch_data["events"].value_counts()

events
field_out                    1178
strikeout                     608
single                        382
walk                          225
double                        104
home_run                       74
force_out                      43
grounded_into_double_play      41
hit_by_pitch                   26
sac_fly                        20
field_error                    19
sac_bunt                       10
fielders_choice                 7
intent_walk                     6
triple                          6
fielders_choice_out             5
truncated_pa                    4
double_play                     3
catcher_interf                  3
strikeout_double_play           1
sac_fly_double_play             1
Name: count, dtype: int64

In [15]:
pitch_data.isnull().sum()

game_date               0
player_name             0
pitcher                 0
batter                  0
pitch_type             27
release_speed          29
release_spin_rate      47
pfx_x                  29
pfx_z                  29
release_pos_x          29
release_pos_z          29
release_extension      27
plate_x                27
plate_z                27
zone                   27
stand                   0
p_throws                0
balls                   0
strikes                 0
description             0
events               7965
dtype: int64

In [16]:
missing_pct = pitch_data.isnull().mean() * 100

missing_pct.sort_values(ascending=False)

events               74.224210
release_spin_rate     0.437983
pfx_x                 0.270245
release_speed         0.270245
release_pos_x         0.270245
pfx_z                 0.270245
release_pos_z         0.270245
plate_x               0.251607
release_extension     0.251607
pitch_type            0.251607
plate_z               0.251607
zone                  0.251607
game_date             0.000000
batter                0.000000
pitcher               0.000000
player_name           0.000000
stand                 0.000000
p_throws              0.000000
balls                 0.000000
strikes               0.000000
description           0.000000
dtype: float64

In [17]:
pitch_data["player_name"].value_counts().head(10)

player_name
Crochet, Garrett    112
Paddack, Chris      110
Bibee, Tanner       107
Megill, Tylor       105
Bradley, Taj        104
Peralta, Freddy     103
Bello, Brayan       103
Williams, Gavin     103
Webb, Logan         102
Morton, Charlie     100
Name: count, dtype: int64

In [19]:
pitcher_name = "Crochet, Garrett"
one_pitcher = pitch_data[
    pitch_data["player_name"] == pitcher_name
].copy()
one_pitcher.head()

,game_date,player_name,pitcher,batter,pitch_type,release_speed,release_spin_rate,pfx_x,pfx_z,release_pos_x,release_pos_z,release_extension,plate_x,plate_z,zone,stand,p_throws,balls,strikes,description,events
0,2025-06-01,"Crochet, Garrett",676979,660670,FC,91.6,2625,-0.26,0.61,2.42,6.24,6.8,0.096549,1.784987,8,R,L,3,2,swinging_strike,strikeout
1,2025-06-01,"Crochet, Garrett",676979,660670,FF,96.5,2438,0.68,1.24,2.54,6.07,6.9,0.400331,2.490734,6,R,L,3,1,foul,NaN
2,2025-06-01,"Crochet, Garrett",676979,660670,FF,96.2,2272,0.39,1.28,2.44,6.18,7.0,-0.62494,1.593072,7,R,L,2,1,ball,NaN
4,2025-06-01,"Crochet, Garrett",676979,660670,FF,96.0,2377,0.57,1.14,2.49,6.17,6.9,-1.687438,2.936153,11,R,L,1,1,ball,NaN
7,2025-06-01,"Crochet, Garrett",676979,660670,FC,93.0,2531,-0.2,0.96,2.61,6.26,6.7,0.837763,2.83696,12,R,L,1,0,called_strike,NaN

In [20]:
one_pitcher["pitch_type"].value_counts()

pitch_type
FF    53
FC    37
ST    14
SI     6
CH     2
Name: count, dtype: int64

## Arsenal Summary

Summarize Crochet's pitch usage and average characteristics by pitch type.

In [22]:
arsenal = one_pitcher.groupby("pitch_type").agg(
    pitches=("pitch_type", "count"),
    avg_velocity=("release_speed", "mean"),
    avg_spin_rate=("release_spin_rate", "mean"),
    avg_horizontal_movement=("pfx_x", "mean"),
    avg_vertical_movement=("pfx_z", "mean")
)
arsenal.round(2)

,pitches,avg_velocity,avg_spin_rate,avg_horizontal_movement,avg_vertical_movement
pitch_type,,,,,
CH,2,87.6,1960.5,1.27,0.51
FC,37,91.89,2601.03,-0.26,0.63
FF,53,96.13,2413.79,0.6,1.3
SI,6,95.58,2338.67,1.22,0.59
ST,14,83.14,2417.21,-1.11,-0.2

In [30]:
arsenal["usage_pct"] = (
    arsenal["pitches"] / arsenal["pitches"].sum()
) * 100
arsenal = arsenal.sort_values(
    by="pitches",
    ascending=False
)
arsenal.round(2)

,pitches,avg_velocity,avg_spin_rate,avg_horizontal_movement,avg_vertical_movement,usage_pct
pitch_type,,,,,,
FF,53,96.13,2413.79,0.6,1.3,47.32
FC,37,91.89,2601.03,-0.26,0.63,33.04
ST,14,83.14,2417.21,-1.11,-0.2,12.50
SI,6,95.58,2338.67,1.22,0.59,5.36
CH,2,87.6,1960.5,1.27,0.51,1.79

## Saving the Sample

The smaller Statcast dataset will be saved locally so that it can be reused without downloading the same data again.

Parquet format is being used because it is efficient for storing larger datasets and preserves data types better than CSV.

In [31]:
pitch_data.to_parquet(
    "../data/raw/statcast_sample.parquet",
    index=False
)

## Initial Takeaways

- Statcast provides pitch level information covering pitch characteristics, movement, location, game context, and outcomes.
- The dataset contains considerably more variables than will be necessary for the initial analysis.
- `description` represents the result of an individual pitch, while `events` generally represents the final result of the plate appearance.
- Missing values do not always represent data quality problems. Some variables, such as `events`, are only expected to contain values for certain pitches.
- Pitch type will need to be considered when comparing pitch characteristics because different pitch types are designed to behave differently.
- A small sample is sufficient for understanding the dataset, but a much larger historical dataset will eventually be required for modeling.